# Generated by Django 3.2.8 on 2021-10-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tweetlike',
            options={'ordering': ['-created_at']},
        ),
    ]
